/**
 * Calibrates activity score percentile tables from Open-Meteo historical archive.
 * Run with: npm run calibrate
 *
 * Fetches 5 years of hourly weather data for 3 Bay Area reference locations,
 * computes the raw activity score (no nighttime penalty) for each hour, and
 * builds an empirical CDF per activity. Output is written to
 * src/lib/percentile-tables.ts and should be committed.
 *
 * Re-run this whenever scoring weights change significantly.
 */

import fs from "fs";
import path from "path";
import { computeRawScore } from "../src/lib/scoring";
import { ACTIVITY_CATALOG } from "../src/lib/activities";
import type { ActivityId } from "../src/lib/types";

// Bay Area reference locations — chosen to capture coastal fog, inland heat,
// and mid-bay conditions that users of this app are likely to experience.
const REFERENCE_LOCATIONS = [
  { name: "San Francisco (coastal)", lat: 37.77, lon: -122.42 },
  { name: "Oakland / Berkeley",      lat: 37.80, lon: -122.27 },
  { name: "San Jose (inland)",       lat: 37.34, lon: -121.89 },
];

const START_DATE = "2020-01-01";
const END_DATE   = "2024-12-31";

// Number of evenly-spaced CDF breakpoints to store per activity.
// 1000 gives 0.1-percentile resolution with a ~32 KB file total.
const N_POINTS = 1000;

interface ArchiveResponse {
  hourly: {
    time: string[];
    apparent_temperature: (number | null)[];
    windspeed_10m: (number | null)[];
    precipitation: (number | null)[];
    cloudcover: (number | null)[];
  };
}

async function fetchArchive(lat: number, lon: number, name: string): Promise<ArchiveResponse> {
  const params = new URLSearchParams({
    latitude:           String(lat),
    longitude:          String(lon),
    start_date:         START_DATE,
    end_date:           END_DATE,
    hourly:             "apparent_temperature,windspeed_10m,precipitation,cloudcover",
    temperature_unit:   "fahrenheit",
    windspeed_unit:     "mph",
    precipitation_unit: "inch",
    timezone:           "America/Los_Angeles",
  });
  const url = `https://archive-api.open-meteo.com/v1/archive?${params}`;
  console.log(`  Fetching ${name} …`);
  const res = await fetch(url, { headers: { "User-Agent": "outdoor-activity-app/1.0" } });
  if (!res.ok) {
    throw new Error(`Archive fetch failed for ${name}: HTTP ${res.status} ${res.statusText}`);
  }
  return res.json() as Promise<ArchiveResponse>;
}

async function main() {
  const allScores = {} as Record<ActivityId, number[]>;
  for (const { id } of ACTIVITY_CATALOG) allScores[id] = [];

  let totalHours = 0;
  let skippedHours = 0;

  for (const loc of REFERENCE_LOCATIONS) {
    const data = await fetchArchive(loc.lat, loc.lon, loc.name);
    const { time, apparent_temperature, windspeed_10m, precipitation, cloudcover } = data.hourly;
    console.log(`  → ${time.length.toLocaleString()} hours`);

    for (let i = 0; i < time.length; i++) {
      const tempF      = apparent_temperature[i];
      const windMph    = windspeed_10m[i];
      const precipInHr = precipitation[i];
      const cloudPct   = cloudcover[i];

      // Skip hours with missing data (rare in archive, but possible at boundaries)
      if (tempF == null || windMph == null || precipInHr == null || cloudPct == null) {
        skippedHours++;
        continue;
      }

      totalHours++;
      for (const { id } of ACTIVITY_CATALOG) {
        allScores[id].push(computeRawScore(id, tempF, windMph, precipInHr, cloudPct));
      }
    }
  }

  console.log(`\nTotal hours used: ${totalHours.toLocaleString()} (skipped ${skippedHours})`);

  // Build sorted CDFs and downsample to N_POINTS evenly-spaced breakpoints.
  console.log("\nPercentile summary (p10 / p50 / p90):");
  const tableEntries: string[] = [];

  for (const { id } of ACTIVITY_CATALOG) {
    const scores = allScores[id];
    scores.sort((a, b) => a - b);

    const sampled: number[] = [];
    const step = (scores.length - 1) / (N_POINTS - 1);
    for (let i = 0; i < N_POINTS; i++) {
      sampled.push(scores[Math.round(i * step)]);
    }

    const p10 = sampled[Math.round(N_POINTS * 0.10)].toFixed(3);
    const p50 = sampled[Math.round(N_POINTS * 0.50)].toFixed(3);
    const p90 = sampled[Math.round(N_POINTS * 0.90)].toFixed(3);
    console.log(`  ${id.padEnd(8)} p10=${p10}  p50=${p50}  p90=${p90}`);

    const values = sampled.map(v => v.toFixed(4)).join(", ");
    tableEntries.push(`  ${id}: new Float32Array([${values}]),`);
  }

  const output = [
    `// AUTO-GENERATED by scripts/calibrate-percentiles.ts — do not edit by hand`,
    `// Generated:  ${new Date().toISOString().split("T")[0]}`,
    `// Reference:  Bay Area (SF coastal, Oakland, San Jose)`,
    `// Period:     ${START_DATE} to ${END_DATE}`,
    `// Hours used: ${totalHours.toLocaleString()} across ${REFERENCE_LOCATIONS.length} locations`,
    `import type { ActivityId } from "./types";`,
    ``,
    `export const PERCENTILE_TABLES: Partial<Record<ActivityId, Float32Array>> = {`,
    ...tableEntries,
    `};`,
    ``,
  ].join("\n");

  const outPath = path.join(process.cwd(), "src/lib/percentile-tables.ts");
  fs.writeFileSync(outPath, output, "utf8");
  console.log(`\nWrote ${outPath}`);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
